### ISSUE TITLE
Return parsed semver of Nodejs version

### ISSUE THREAD

**Issue by shuhrat** [ehmicky/preferred-node-version#13]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

👋  Hi there!

First of all thank you for your work.  Is there any ideas to add `parse: boolean` option? 

Now returned value is a raw string. But in many cases version is parsed, suppose that this case is fairly common case.

### Describe the solution you'd like

On `parse: true` returned value is parsed semver value with major, minor, and patch.

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @shuhrat,

Thanks a lot for your input.

I agree that this should be a common use case, especially retrieving the major release number.
However, it should be fairly simple to do for users using [`semver`](https://github.com/npm/node-semver) directly:

```js
import preferredNodeVersion from 'preferred-node-version'
import { major } from 'semver'

const { version } = await preferredNodeVersion()
console.log(major(version)) // 19
```

Keeping the API simple is important for this small project, so I would favor modularity instead in this case.

That being case, thanks for suggesting this feature. :pray:
